export const lightTheme = {
  dark: false,
  colors: {
    primary: '#4F46E5',
    primaryLight: '#EEF2FF',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    text: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    divider: '#F1F5F9',
    error: '#EF4444',
    success: '#22C55E',
    warning: '#F59E0B',
    info: '#3B82F6',
    // Status colors
    statusOpen: '#3B82F6',
    statusOpenBg: '#EFF6FF',
    statusInProgress: '#F59E0B',
    statusInProgressBg: '#FFFBEB',
    statusResolved: '#22C55E',
    statusResolvedBg: '#F0FDF4',
    statusClosed: '#94A3B8',
    statusClosedBg: '#F8FAFC',
    // Priority colors
    priorityLow: '#22C55E',
    priorityLowBg: '#F0FDF4',
    priorityMedium: '#F59E0B',
    priorityMediumBg: '#FFFBEB',
    priorityHigh: '#EF4444',
    priorityHighBg: '#FEF2F2',
    priorityCritical: '#7C3AED',
    priorityCriticalBg: '#F5F3FF',
    // Misc
    shadow: '#000',
    inputBackground: '#F8FAFC',
    placeholder: '#94A3B8',
  },
  fonts: {
    heading: 'SpaceGrotesk-Bold',
    headingMedium: 'SpaceGrotesk-Medium',
    headingRegular: 'SpaceGrotesk-Regular',
    body: 'Satoshi-Regular',
    bodyMedium: 'Satoshi-Medium',
    bodyBold: 'Satoshi-Bold',
  },
};

export const darkTheme = {
  dark: true,
  colors: {
    primary: '#818CF8',
    primaryLight: '#1E1B4B',
    background: '#0F172A',
    surface: '#1E293B',
    surfaceElevated: '#263548',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    textMuted: '#64748B',
    border: '#334155',
    divider: '#1E293B',
    error: '#F87171',
    success: '#4ADE80',
    warning: '#FCD34D',
    info: '#60A5FA',
    // Status colors
    statusOpen: '#60A5FA',
    statusOpenBg: '#1E3A5F',
    statusInProgress: '#FCD34D',
    statusInProgressBg: '#3D2B00',
    statusResolved: '#4ADE80',
    statusResolvedBg: '#052E16',
    statusClosed: '#64748B',
    statusClosedBg: '#1E293B',
    // Priority colors
    priorityLow: '#4ADE80',
    priorityLowBg: '#052E16',
    priorityMedium: '#FCD34D',
    priorityMediumBg: '#3D2B00',
    priorityHigh: '#F87171',
    priorityHighBg: '#3B0000',
    priorityCritical: '#A78BFA',
    priorityCriticalBg: '#2E1065',
    // Misc
    shadow: '#000',
    inputBackground: '#1E293B',
    placeholder: '#64748B',
  },
  fonts: {
    heading: 'SpaceGrotesk-Bold',
    headingMedium: 'SpaceGrotesk-Medium',
    headingRegular: 'SpaceGrotesk-Regular',
    body: 'Satoshi-Regular',
    bodyMedium: 'Satoshi-Medium',
    bodyBold: 'Satoshi-Bold',
  },
};

export type Theme = typeof lightTheme;
